# -------------------------------- Service ---------------------------
#
service:
  name: hall
  port: 19118
  #
  # registered in the service center [zookeepr or etcd], exposed to the
  # external address information
  #
  address:
  #
  # service lbs strategy options[polling,hashing]
  #
  lbs: polling
# -------------------------------- Database ---------------------------
database:
  address: 127.0.0.1:27017
  name: db_hall
# -------------------------------- Cache ---------------------------
cache:
  address: 127.0.0.1:6379
  password:
# -------------------------------- Custom ---------------------------
#param1: 11111111
#param2: e434e639